[tool.poetry]
name = "cookbook"
version = "0.1.0"
description = ""
authors = ["Adam Benda <adam@adasek.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
flask = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
